<?php

namespace Database\Seeders;

use App\Models\Objetivo;
use Illuminate\Database\Seeder;

class objetivosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $objetivos = [
            ['descripcion'=>'Aplicar modelos matemáticos para la resolución de problemas informáticos, técnicos, de las ciencias básicas y administrativas.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Elaborar documentos de soporte para usuarios.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Realizar la modelación de objetos, utilizando UML	', 'nivel_id'=>'1'],
            ['descripcion'=>'Desarrollar una estrategia para solucionar problemas con la ayuda de métodos estandarizados.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Distinguir y clasificar lenguajes de programación.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar algoritmos en paradigmas de programación en seudocodigo	', 'nivel_id'=>'1'],
            ['descripcion'=>'Utilizar un entorno de programación (plataforma) para la programación.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar las diferentes instrucciones, funciones internas y operaciones matematicas para la resolución de  de problemas usando lenguajes de programación.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar estructuras selectivas y repetitivas para la resolución de problemas usando lenguajes de programación (for , do, while, if)	', 'nivel_id'=>'1'],
            ['descripcion'=>'Considerar los derechos y obligaciones de la relación de formación entre empresa formadora y estudiante.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Manipular HTML y DOOM, diferencias.', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar estructuras de Datos (arrays) en la resolución de problemas usadno lenguajes de programación	', 'nivel_id'=>'1'],
            ['descripcion'=>'Considerar los reglamentos legales y reglamentos internos de la empresa formadora.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Abstraer situaciones empresariales diarias y hasta convertirlas en figuras, diagramas o relaciones.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Elegir algoritmos en la realización de pliegos de condiciones, en particular los conceptos básicos como secuencias, selección e iteración.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Describir tareas, organización y estructuras de decisiones en la empresa.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Describir la forma legal de la empresa formadora.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Describir la relación de la empresa formadora con las organizaciones del sector productivo, gremios e instituciones públicas.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Explicar el objetivo y los campos de actividad de la empresa formadora y su posición en el mercado.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Comparar el plan de rotación con el plan marco de formación.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Definir el cronograma y la secuencia de los pasos de trabajo para el propio ámbito de trabajo, planificar y coordinar fechas.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Conocer las claúsulas fundamentales del contrato de formación dual entre la empresa formadora y la IES.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Desarrollar la disposición del aprendizaje continuo e investigar las posibilidades de capacitación y formación continua.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Analizar riesgos de trabajo en la empresa, para prevenir accidentes.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar plan de contingencia en caso de un desastre (incendio, accidente, fenómenos naturales, etc).	', 'nivel_id'=>'1'],
            ['descripcion'=>'Contribuir a la preservación del medio del medio ambiente y reducir riesgos del trabajo del estudiante y la empresa.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Aplicar  las normas de imagen coorporativa y personales, observando espacios confortables y ergonómicos tanto para el cliente interno como para el externo.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Proponer medidas para la optimización de procesos en el desarrollo y organización de la empresa.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Planificar tareas y trabajarlos en equipo, coordinar los resultados y analizarlos.	', 'nivel_id'=>'1'],
            ['descripcion'=>'Manipular lenguaje phyton	', 'nivel_id'=>'1'],
            ['descripcion'=>'Abstraer situaciones empresariales diarias y hasta convertirlas en figuras, diagramas o relaciones.', 'nivel_id'=>'2'],
            ['descripcion'=>'Realizar la modelación de objetos, con un lenguaje de marcado estandarizado.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Desarrollar una estrategia para solucionar problemas con la ayuda de métodos estandarizados.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Convertir modelos de objetos en tipos de datos elementales y en todas las estructuras de datos compuestos, los evalúa con respeto a tipos de almacenamiento y aplicación de los métodos de acceso.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Diagramar modelos entidad-relación de situaciones empresariales reales.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Crear bases de datos estructuradas con la ayuda de un lenguaje estandarizado.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Distinguir y clasificar lenguajes de programación.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Realizar diagramas de clases con un método estandarizado.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Programar con lenguajes orientados a objetos usando estandares y aplicando sentencias para resolver algoritmos simples.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Programar con lenguaje estandarizado para la definición, manipulación y gestión de datos.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Gestionar la información almacenada en una base de datos usando lenguaje estarizado de consultas.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Describir tareas, organización y estructuras de decisiones en la empresa.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Describir la forma legal de la empresa formadora.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Describir la relación de la empresa formadora con las organizaciones del sector productivo, gremios y instituciones públicas.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Explicar el objetivo y los campos de actividad de la empresa formadora y su posición en el mercado.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Considerar los derechos y obligaciones de la relación de formación entre empresa formadora y estudiante.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Comparar el plan de rotación con el plan marco de formación.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Considerar los reglamentos legales y reglamentos internos de la empresa formadora.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Nombrar las clausulas fundamentales del contrato de formación entre empresa formadora y estudiante.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Desarrollar la disposición del aprendizaje continuo e investigar las posibilidades de capacitación y formación continua.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Constatar peligros para seguridad y salud en el lugar de trabajo y tomar medidas para evitarlos.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Aplicar reglamentos para protección de trabajo y evitar accidentes.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Describir el comportamiento y las medidas en caso de accidentes e iniciar primeras medidas.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Aplicar medidas de seguridad contra incendios, describir los comportamientos adecuados en caso de incendios.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Realizar un análisis de las tareas y decidir la forma de organizar el trabajo.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Planificar tareas y trabajarlos en equipo, coordinar los resultados y analizarlos.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Organizar el propio lugar de trabajo considerando los lineamientos de la empresa formadora y aspectos ergonómicos.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Proponer medidas para la mejora de la organización de trabajo.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Usar los medios y herramientas de trabajo y organización de una forma eficiente.	', 'nivel_id'=>'2'],
            ['descripcion'=>'Planificar tareas y trabajarlos en equipo, coordinar los resultados y analizarlos.	', 'nivel_id'=>'2'],
           
            ['descripcion'=>'Desarrollar páginas web estáticas utilizando un lenguaje de marcado.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Aplicar métodos criptográficos.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Aplicar modelos matemáticos para la resolución de problemas informáticos, técnicos, de las ciencias básicas y administrativas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Utilizar frameworks de diseño y hojas de estilo en cascada aplicadas a páginas web estáticas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Crear páginas web dinámicas utilizando la arquitectura cliente - servidor.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Elaborar documentos de soporte para usuarios.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Identificar procesos continuos y discontinuos.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Diagramar modelos entidad-relación de situaciones empresariales reales.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Analizar procesos discretos con ayuda de sucesiones y series matemáticas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Realizar la modelación de objetos, con un lenguaje de marcado estandarizado.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Desarrollar una estrategia para solucionar problemas con la ayuda de métodos estandarizados.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Crear bases de datos estructuradas con la ayuda de un lenguaje estandarizado.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Distinguir y clasificar lenguajes de programación.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Analizar la complejidad de algoritmos al respecto de tiempo de ejecución, espacio de memoria y propensión a errores, y dictamen del esfuerzo de la programación. 	', 'nivel_id'=>'3'],
            ['descripcion'=>'Realizar diagramas de clases con un método estandarizado.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Programar con lenguaje estandarizado, orientado a objetos, para la definición, manipulación y gestión de datos.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Programar un API REST	', 'nivel_id'=>'3'],
            ['descripcion'=>'Diseñar interfases de usuario (UX)	', 'nivel_id'=>'3'],
            ['descripcion'=>'Gestionar la información almacenada en una base de datos usando lenguaje estandarizado de consultas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Aplicar un entorno de programación (plataforma) para la programación.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Considerar los derechos y obligaciones de la relación de formación entre empresa formadora y estudiante.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Considerar los reglamentos legales y reglamentos internos de la empresa formadora.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Abstraer situaciones empresariales diarias y hasta convertirlas en figuras, diagramas o relaciones.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Elegir algoritmos en la realización de pliegos de condiciones, en particular los conceptos básicos como secuencias, selección e iteración.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Describir tareas, organización y estructuras de decisiones en la empresa.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Describir la forma legal de la empresa formadora.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Describir la relación de la empresa formadora con las organizaciones del sector productivo, gremios e instituciones públicas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Explicar el objetivo y los campos de actividad de la empresa formadora y su posición en el mercado.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Comparar el plan de rotación con el plan marco de formación.', 'nivel_id'=>'3'],
            ['descripcion'=>'Definir el cronograma y la secuencia de los pasos de trabajo para el propio ámbito de trabajo, planificar y coordinar fechas.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Conocer las claúsulas fundamentales del contrato de formación dual entre la empresa formadora y la IES. 	', 'nivel_id'=>'3'],
            ['descripcion'=>'Desarrollar la disposición del aprendizaje continuo e investigar las posibilidades de capacitación y formación continua.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Analizar riesgos de trabajo en la empresa, para prevenir accidentes.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Aplicar plan de contingencia en caso de un desastre (incendio, accidente, fenómenos naturales, etc.).	', 'nivel_id'=>'3'],
            ['descripcion'=>'Contribuir a la preservación del medio del medio ambiente y reducir riesgos del trabajo del estudiante y la empresa.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Aplicar las normas de imagen coorporativa y personales, observando espacios confortables y ergonómicos tanto para el cliente interno como para el externo	', 'nivel_id'=>'3'],
            ['descripcion'=>'Proponer medidas para la optimización de procesos en el desarrollo y organización de la empresa.	', 'nivel_id'=>'3'],
            ['descripcion'=>'Conocer los fundamentos de la administración de la empresa	', 'nivel_id'=>'3'],
            ['descripcion'=>'Planificar tareas y trabajarlos en equipo, coordinar los resultados y analizarlos.	', 'nivel_id'=>'3'],
            

            ['descripcion'=>'Construir interfaces gráficas utilizando HTML5 y CSS3 para integrar en aplicaciones web.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Programar con lenguaje javascript y typescript para manejar el modelo en cliente.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Utilizar angular en una página HTML para mapear la vista y el modelo.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Generar solicitudes HTTP y administrar servidores web para exponer y consumir servicios web.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Comprender los patrones MVC y MVVM para estructurar adecuadamente los componentes de una aplicación web.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Elaborar documentos de soporte para usuarios.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Identificar procesos continuos y discontinuos.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Diagramar modelos entidad-relación de situaciones empresariales reales.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Construir  servicios REST y servicios con estado, para permitir el consumo de datos desde un cliente.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Realizar la modelación de objetos, con un lenguaje de marcado estandarizado.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Desarrollar una estrategia para solucionar problemas con la ayuda de métodos estandarizados.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Crear bases de datos estructuradas con la ayuda de un lenguaje estandarizado.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Distinguir y clasificar lenguajes de programación.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Analizar la complejidad de algoritmos al respecto de tiempo de ejecución, espacio de memoria y propensión a errores, y dictamen del esfuerzo de la programación. 	', 'nivel_id'=>'4'],
            ['descripcion'=>'Realizar diagramas de clases con un método estandarizado.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Programar con lenguaje estandarizado, orientado a objetos, para la definición, manipulación y gestión de datos.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Implementar aplicaciones Single Page Applications (SPA) que se carguen por componentes para una navegación óptima.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Explicar los procedimientos de vigilancia y seguridad para la implementación en las aplicaciones.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Gestionar los datos almacenados en el equipo de forma segura para la utilización en la aplicación	', 'nivel_id'=>'4'],
            ['descripcion'=>'Aplicar un entorno de programación (plataforma) para la programación.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Considerar los derechos y obligaciones de la relación de formación entre empresa formadora y estudiante.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Considerar los reglamentos legales y reglamentos internos de la empresa formadora.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Abstraer situaciones empresariales diarias y hasta convertirlas en figuras, diagramas o relaciones.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Elegir algoritmos en la realización de pliegos de condiciones, en particular los conceptos básicos como secuencias, selección e iteración.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Describir tareas, organización y estructuras de decisiones en la empresa.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Describir la forma legal de la empresa formadora.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Describir la relación de la empresa formadora con las organizaciones del sector productivo, gremios e instituciones públicas.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Explicar el objetivo y los campos de actividad de la empresa formadora y su posición en el mercado.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Comparar el plan de rotación con el plan marco de formación.', 'nivel_id'=>'4'],
            ['descripcion'=>'Definir el cronograma y la secuencia de los pasos de trabajo para el propio ámbito de trabajo, planificar y coordinar fechas.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Conocer las claúsulas fundamentales del contrato de formación dual entre la empresa formadora y la IES. 	', 'nivel_id'=>'4'],
            ['descripcion'=>'Desarrollar la disposición del aprendizaje continuo e investigar las posibilidades de capacitación y formación continua.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Analizar riesgos de trabajo en la empresa, para prevenir accidentes.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Aplicar plan de contingencia en caso de un desastre (incendio, accidente, fenómenos naturales, etc.).	', 'nivel_id'=>'4'],
            ['descripcion'=>'Contribuir a la preservación del medio del medio ambiente y reducir riesgos del trabajo del estudiante y la empresa.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Aplicar las normas de imagen coorporativa y personales, observando espacios confortables y ergonómicos tanto para el cliente interno como para el externo	', 'nivel_id'=>'4'],
            ['descripcion'=>'Proponer medidas para la optimización de procesos en el desarrollo y organización de la empresa.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Conocer los fundamentos de la administración de la empresa	', 'nivel_id'=>'4'],
            ['descripcion'=>'Planificar tareas y trabajarlos en equipo, coordinar los resultados y analizarlos.	', 'nivel_id'=>'4'],
            ['descripcion'=>'Emplear los sensores y eventos según su configuración del equipo para obtener datos que utilice la aplicación.	', 'nivel_id'=>'4'],

            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
            // ['descripcion'=>'', 'nivel_id'=>'5'],
                    
            
        ];
        Objetivo::insert($objetivos);
    }
}
